force-app/main/default/objects/Genre__c/Genre__c.object-meta.xml
<CustomObject>
    <label>Genre</label>
    <nameField>
        <label>Genre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist__c/Playlist__c.object-meta.xml
<CustomObject>
    <label>Playlist</label>
    <nameField>
        <label>Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Playlists</relationshipLabel>
    <relationshipName>Playlists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Playlist__c/Playlist__c.field-meta.xml
<CustomField>
    <fullName>Playlist__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Playlist</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Playlist_Song_Junction__c/Playlist_Song_Junction__c.object-meta.xml
<CustomObject>
    <label>Playlist Song Junction</label>
    <nameField>
        <displayFormat>TRACK-{0000}</displayFormat>
        <label>Playlist Song Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playlist Song Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist_Song_Junction__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <externalId>true</externalId>
    <label>Genre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Playlist_Song_Junction__c/fields/Playlist__c.field-meta.xml
<CustomField>
    <fullName>Playlist__c</fullName>
    <label>Playlist</label>
    <referenceTo>Playlist__c</referenceTo>
    <relationshipLabel>Songs</relationshipLabel>
    <relationshipName>Playlist_Songs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Playlist_Song_Junction__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Playlists</relationshipLabel>
    <relationshipName>Song_Playlists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genre_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Song__c/fields/Singer__c.field-meta.xml
<CustomField>
    <fullName>Singer__c</fullName>
    <label>Singer</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Genre_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Jazz</fullName>
    </customValue>
    <customValue>
        <fullName>Pop</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Disco</fullName>
    </customValue>
    <customValue>
        <fullName>Instrumental</fullName>
    </customValue>
    <masterLabel>Genre List</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PlaylistSongTest.cls
@isTest
public class PlaylistSongTest {
	
    @testsetup
    public static void createTestData(){
        List<Contact> contacts = TestService.createContacts(5,true);
        List<Playlist__c> playlists = TestService.createPlaylists(5, contacts, 'Pop');
        List<Song__c> popSongs = TestService.createSongs(5, 'Pop');
        List<Song__c> rockSongs = TestService.createSongs(5, 'Rock');
    }
    
    @istest
    public static void addSongToPlaylistTest(){
        Test.startTest();
        List<Playlist__c> playlists = [SELECT Name, Id, Contact__c, Genres__c FROM Playlist__c];
        List<Song__c> popSongs = [SELECT Name, Id, Genre__c, Singer__c, Release_Date__c FROM Song__c WHERE Genre__c = 'Pop'];
        List<Song__c> rockSongs = [SELECT Name, Id, Genre__c, Singer__c, Release_Date__c FROM Song__c WHERE Genre__c = 'Rock'];
//        List<Playlist_Song_Junction__c> = TestService.addSongToPlaylist(5, playlists, songs);
		List<Playlist_Song_Junction__c> psjList = new List<Playlist_Song_Junction__c>();
        for(Integer i = 0; i<5; i++){
            Playlist_Song_Junction__c psj = new Playlist_Song_Junction__c(Song__c = popSongs[i].Id, Playlist__c = playlists[i].Id);
            psjList.add(psj);
        }         
        insert psjList;
        system.assertEquals(5, psjList.size());
        
        //Adding duplicates
		List<Playlist_Song_Junction__c> psjList2 = new List<Playlist_Song_Junction__c>();
        for(Integer i = 0; i<5; i++){
            Playlist_Song_Junction__c psj = new Playlist_Song_Junction__c(Song__c = popSongs[i].Id, Playlist__c = playlists[i].Id);
            psjList.add(psj);
        }         
        insert psjList2;
        
        //Adding wrong genre
		List<Playlist_Song_Junction__c> psjList3 = new List<Playlist_Song_Junction__c>();
        for(Integer i = 0; i<5; i++){
            Playlist_Song_Junction__c psj = new Playlist_Song_Junction__c(Song__c = rockSongs[i].Id, Playlist__c = playlists[i].Id);
            psjList.add(psj);
        }         
        insert psjList3;
        Test.stopTest();
    }
}