force-app/main/default/objects/Contact/fields/Subscribe_to_new_songs__c.field-meta.xml
<CustomField>
    <fullName>Subscribe_to_new_songs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscribe to new songs?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Genre__c/Genre__c.object-meta.xml
<CustomObject>
    <label>Genre</label>
    <nameField>
        <label>Genre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist__c/Playlist__c.object-meta.xml
<CustomObject>
    <label>Playlist</label>
    <nameField>
        <label>Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Playlists</relationshipLabel>
    <relationshipName>Playlists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Playlist__c/fields/Genre_s__c.field-meta.xml
<CustomField>
    <fullName>Genre_s__c</fullName>
    <label>Genre(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genre_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Playlist__c/Playlist__c.field-meta.xml
<CustomField>
    <fullName>Playlist__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Playlist</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Playlist_Song_Junction__c/Playlist_Song_Junction__c.object-meta.xml
<CustomObject>
    <label>Playlist Song Junction</label>
    <nameField>
        <displayFormat>TRACK-{0000}</displayFormat>
        <label>Playlist Song Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playlist Song Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist_Song_Junction__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <externalId>true</externalId>
    <label>Genre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Playlist_Song_Junction__c/fields/Playlist__c.field-meta.xml
<CustomField>
    <fullName>Playlist__c</fullName>
    <label>Playlist</label>
    <referenceTo>Playlist__c</referenceTo>
    <relationshipLabel>Songs</relationshipLabel>
    <relationshipName>Playlist_Songs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Playlist_Song_Junction__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Playlists</relationshipLabel>
    <relationshipName>Song_Playlists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genre_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Song__c/fields/Singer__c.field-meta.xml
<CustomField>
    <fullName>Singer__c</fullName>
    <label>Singer</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Genre_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Jazz</fullName>
    </customValue>
    <customValue>
        <fullName>Pop</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Disco</fullName>
    </customValue>
    <customValue>
        <fullName>Instrumental</fullName>
    </customValue>
    <masterLabel>Genre List</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestService.cls
@isTest
public class TestService {
    
    //Create Bulk Contacts
    public static List<Contact> createContacts(Integer numContacts, Boolean subscriber){
        
        List<Contact> conts = new List<Contact>();
        for(Integer i = 0; i< numContacts; i++){           
                Contact cont = new Contact(LastName = 'Test' + i, Subscribe_to_new_songs__c = subscriber);   
            	conts.add(cont);
        }
        insert conts;
        return conts;        
    }
    
    //Create bulk Songs
    public static List<Song__c> createSongs(Integer numSongs, String genre){
        List<Song__c> songs = new List<Song__c>();
        for(Integer i = 0; i<numSongs; i ++){
            Song__c song = new Song__c(Name =  'Song' + i, Genre__c = genre, Singer__c = 'Singer ' + i, Title__c =  'Song' + i, Release_Date__c = Date.today() );
            songs.add(song);
        }
        insert songs;
        return songs;
    }
    
    //Create bulk playlists
    public static List<Playlist__c> createPlaylists(Integer numPlaylists, List<Contact> contacts, String genre){
        List<Playlist__c> playlist = new List<Playlist__c>();
        for(Integer i = 0; i<numPlaylists; i ++){
            Playlist__c plist = new Playlist__c(Name = 'Playlist' + i, Contact__c = contacts[i].Id, Genre_s__c = genre, Genres__c = genre);
            playlist.add(plist);
        }
        insert playlist;
        return playlist;
    }
    
    
    //create bulk playlist-song junction object
    public static List<Playlist_Song_Junction__c> addSongToPlaylist(Integer numRecs, List<Playlist__c> playlists, List<Song__c> songs){
        List<Playlist_Song_Junction__c> psjList = new List<Playlist_Song_Junction__c>();
        for(Integer i = 0; i<numRecs; i++){
            Playlist_Song_Junction__c psj = new Playlist_Song_Junction__c(Song__c = songs[i].Id, Playlist__c = playlists[i].Id);
            psjList.add(psj);
        }         
        insert psjList;
        return psjList;
    }

}