force-app/main/default/objects/Contact/fields/Subscribe_to_new_songs__c.field-meta.xml
<CustomField>
    <fullName>Subscribe_to_new_songs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscribe to new songs?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Genre__c/Genre__c.object-meta.xml
<CustomObject>
    <label>Genre</label>
    <nameField>
        <label>Genre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist__c/Playlist__c.object-meta.xml
<CustomObject>
    <label>Playlist</label>
    <nameField>
        <label>Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Playlists</relationshipLabel>
    <relationshipName>Playlists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Playlist__c/Playlist__c.field-meta.xml
<CustomField>
    <fullName>Playlist__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Playlist</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Playlist_Song_Junction__c/Playlist_Song_Junction__c.object-meta.xml
<CustomObject>
    <label>Playlist Song Junction</label>
    <nameField>
        <displayFormat>TRACK-{0000}</displayFormat>
        <label>Playlist Song Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playlist Song Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist_Song_Junction__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <externalId>true</externalId>
    <label>Genre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Playlist_Song_Junction__c/fields/Playlist__c.field-meta.xml
<CustomField>
    <fullName>Playlist__c</fullName>
    <label>Playlist</label>
    <referenceTo>Playlist__c</referenceTo>
    <relationshipLabel>Songs</relationshipLabel>
    <relationshipName>Playlist_Songs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Playlist_Song_Junction__c/fields/Song__c.field-meta.xml
<CustomField>
    <fullName>Song__c</fullName>
    <label>Song</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipLabel>Playlists</relationshipLabel>
    <relationshipName>Song_Playlists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genre_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Genre_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Jazz</fullName>
    </customValue>
    <customValue>
        <fullName>Pop</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Disco</fullName>
    </customValue>
    <customValue>
        <fullName>Instrumental</fullName>
    </customValue>
    <masterLabel>Genre List</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SongHelper.cls
//This class is called by the SongHandler class
public class SongHelper {
	private static Map<String, List<String>> genrePlaylistMap = new Map<String, List<String>>();
    private static Set<String> songGenres = new Set<String>();
    private static List<Playlist_Song_Junction__c> songPlaylist = new List<Playlist_Song_Junction__c>();
	private List<Song__c> songs = new List<Song__c>();
    private Set<String> subscribedPlaylists = new Set<String>();
    
    public SongHelper(List<Song__c> songs){
        this.songs = songs;
        this.subscribedPlaylists = getSubscriberPlaylists();
        getSongGenres(this.songs);
        initializeGenrePlaylistMap();
        createGenrePlaylistMap(this.subscribedPlaylists);
        linkSongsToPlaylist(this.songs);
    }
    
     //Method to get the playlists of all contacts who have subscribed to new songs
     private static Set<String> getSubscriberPlaylists(){
        Set<String> playlists = new Set<String>();
        for(Playlist__c playlist: [SELECT Id
                				   FROM Playlist__c 
                				   WHERE Contact__r.Subscribe_to_new_songs__c = true])
        {
            playlists.add(playlist.Id);
        }
        system.debug('getSubscriberPlaylists ' + playlists);
        return playlists;
    }
	
	//Initialize a map of the genre and the playlists that can accept that genre    
    private static void initializeGenrePlaylistMap(){
        for(String genre: songGenres){ 
            
            genrePlaylistMap.put(genre, new List<String>() );
        }        
        system.debug('initializeGenrePlaylistMap ' + genrePlaylistMap);
    }

    //construct a map of the genre and the playlists that can accept that genre    
    private static void createGenrePlaylistMap(Set<String> playlists){
        system.debug('playlists= ' + playlists);
        List<String> temp;
        for(Playlist_Song_Junction__c psj: [SELECT Genre__c, Playlist__c  FROM Playlist_Song_Junction__c WHERE Playlist__c IN :playlists ]){
			system.debug('psj.Genre__c ' + psj.Genre__c);
            system.debug('psj.Genre__c ' + psj.Playlist__c);
            if(genrePlaylistMap.containsKey(psj.Genre__c))
            {
                temp = genrePlaylistMap.get(psj.Genre__c);
                system.debug('temp ' + temp);
            	temp.add(psj.Playlist__c);
                system.debug('psj.Playlist__c ' + psj.Playlist__c);
            	system.debug('temp 2' + temp);
            	genrePlaylistMap.put(psj.Genre__c, temp);
            }
            
        }
        
        system.debug('createGenrePlaylistMap ' + genrePlaylistMap);
    }
    
    //Method to get all the different genres of the new songs
    private static void getSongGenres(List<Song__c> songs){
        for(Song__c song: songs){
            songGenres.add(song.Genre__c);
        }
        
        system.debug('getSongGenres ' + songGenres);
    }
    
    //Method to create a complete Playlist_Song_Junction__c record and insert it
    private static void linkSongsToPlaylist(List<Song__c> songs){
        
        for(Song__c song: songs){
            List<String> playlists = new List<String>();
            playlists = genrePlaylistMap.get(song.Genre__c);
            for(String playlist: playlists){
                Playlist_Song_Junction__c record = new Playlist_Song_Junction__c();
                //record.Genre__c = song.Genre__c;
                record.Playlist__c = playlist;
                record.Song__c = song.Id;
                
                songPlaylist.add(record);
                
            }
        }
        system.debug('linkSongsToPlaylist ' + songPlaylist);
        if(songPlaylist.size() > 0){
           insert songPlaylist; 
        }
        
        
    }
}